name: Deploy to VPS

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key & known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "$KNOWN_HOSTS"  > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: SSH & deploy
        run: |
          ssh -o StrictHostKeyChecking=yes \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd unisqoool
            git pull
            npm install
            npm run build
            pm2 restart 0
          EOF
