# .github/workflows/deploy.yml
name: Deploy to VPS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: SSH & Run Deploy Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key & known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$PRIVATE_KEY"   > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          printf '%s\n' "$KNOWN_HOSTS"    > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: SSH & run deploy.sh on VPS
        run: |
          ssh -o StrictHostKeyChecking=yes \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
              'bash -l ~/unisqoool/deploy.sh'
